= Home
:page-aliases: root, home

Welcome, this is where I store my writeups for various challenges such as Wargames, Capture The Flags, Pwn boxes, and etc!!

[%header, format=csv]
|===
Date,Category,Challenge
"2023/11/20","Forensics",             "xref:Root-Me:telnet_authentication.adoc[TELNET - authentication]"
"2023/11/21","Forensics",             "xref:Root-Me:twitter_authentication.adoc[Twitter authentication]"
"2023/11/23","Forensics",             "xref:Root-Me:ftp_authentication.adoc[FTP - authentication]"
"2024/05/09","Forensics",             "xref:HackTheBox:photon_lockdown.adoc[Photon Lockdown]"
"2024/05/19","Forensics",             "xref:HackTheBox:cat.adoc[Cat]"
"2024/05/19","Pwning",                "xref:HackTheBox:bizness.adoc[Bizness]"
"2024/06/19","Pwning",                "xref:HackTheBox:perfection.adoc[Perfection]"
"2024/11/07","Reverse Engineering",   "xref:crackmes.one:keyg3nme/keyg3nme.adoc[keyg3nme]"
"2024/11/09","Reverse Engineering",   "xref:crackmes.one:crackme2-be-D4RK_FL0W/crackme2-be-D4RK_FL0W.adoc[crackme2-be-D4RK_FL0W]"
"2025/03/25","Forensics",             "xref:HackTheBox:a-new-hire.adoc[A new Hire]"
"2025/03/25","Forensics",             "xref:HackTheBox:thorins-amulet.adoc[Thorin’s Amulet]"
"2025/06/12","Reverse Engineering",   "xref:crackmes.one:Crack3-by-D4RK_FL0W/Crack3-by-D4RK_FL0W.adoc[Crack3-by-D4RK_FL0W]"
"2025/06/12","Reverse Engineering",   "xref:crackmes.one:Crackme-4/Crackme-4.adoc[Crackme-4]"
"2025/06/13","Reverse Engineering",   "xref:HackTheBox:rev_spookypass.adoc[SpookyPass]"
|===
